### Criar UF
POST http://localhost:3000/ufs
Content-Type: application/json

{
  "nome": "Distrito Federal",
  "sigla": "DF"
}

### Criar Cidade vinculada à UF 1
POST http://localhost:3000/cidades
Content-Type: application/json

{
  "nome": "Brasília",
  "ufId": 1
}

### Criar Estudante vinculado à Cidade 1
POST http://localhost:3000/estudantes
Content-Type: application/json

{
  "nome": "Lucas",
  "idade": 22,
  "cidadeId": 1
}

### Criar vários estudantes de uma cidade
POST http://localhost:3000/cidades/1/estudantes
Content-Type: application/json

[
  { "nome": "João", "idade": 18 },
  { "nome": "Maria", "idade": 20 }
]

### Listar UFs com cidades
GET http://localhost:3000/ufs

### Listar cidades com estudantes
GET http://localhost:3000/cidades

### Listar estudantes com cidade
GET http://localhost:3000/estudantes
